export ZSH_DISABLE_COMPFIX=true
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(aliases macos git tmux golang docker-compose)
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GOPATH=$HOME/Projects/go
export GOBIN=$GOPATH/bin
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/tmux"
export CDPATH=$GOPATH/src
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export FZF_DEFAULT_OPTS="--color=gutter:#282828 --color=hl+:#ffb964 --reverse"
export EDITOR=nvim

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

alias vim='nvim'
alias tm='tmux new -s ${PWD##*/}'
alias rg='rg --hidden'
alias coverage='go test -coverprofile=c.out ./... && go tool cover -html=c.out && rm c.out'

[ -f ~/.zshcustom ] && source ~/.zshcustom
