export ZSH_DISABLE_COMPFIX=true
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git tmux)
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GOPATH=$HOME/Projects/go
export GOBIN=$GOPATH/bin
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/tmux"
export PATH="$PATH:$HOME/.gem/ruby/2.6.0/bin"
export CDPATH=$GOPATH/src
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export FZF_DEFAULT_OPTS="--color=gutter:#282828 --color=hl+:#ffb964 --reverse"
export EDITOR=vim
alias rg='rg --hidden'
alias coverage='go test -coverprofile=c.out ./... && go tool cover -html=c.out && rm c.out'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs'
[ -f ~/.zshcustom ] && source ~/.zshcustom


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

